### ISSUE TITLE
3 Bugs

### ISSUE THREAD

**Issue by NoHoPeLess** [addstar/BlockHunt#5]
Hello i make this issue from: https://github.com/Steffion/BlockHunt/issues/324

Many people have the same issue:

Quote from eglbogle:

"While playing Block Hunt, there are 3 different glitches I found that are game-breaking:

1. The Block Chooser doesn't work even with all given permissions. When you try to select the block from the inventory that it pulls up, it takes the block out like it's a chest.

2. Hiders can't kill or damage in any way harm the Seekers because they're in godmode.

3. Hiders are invisible when they begin to hide. As long as they're moving, they will remain invisible.

Are there any fixes for these glitches?"

So this are my logs and configs:

We use :
-Spigot-1649
-ProtocolLib v3.6.0-SNAPSHOT
-LibsDisguises v8.2.6
-BlockHunt v0.2.1-b26

Serverlog: http://pastebin.com/4im2xmnn

Config: http://pastebin.com/nE7Uz0tE

Arenas: http://pastebin.com/9BczQTCv

Hope this helps to solve the bugs

**Comment by eglbogle** [comment]
Yeah, I have the same issue as well. Also, when I tried using a more recent release, then the formerly vulnerable hiders now didn't take damage. They made sounds like they were dying, but never actually died. I tried this, and I made the damage sounds, but I didn't actually take any damage.

**Comment by Sebyoyo16** [comment]
I have a problem i can't change de messages, because i want to translate it in french .

**Comment by NoHoPeLess** [comment]
Sebyoyo16 you write it in an wrong issue, pls make a new issue for this

**Comment by addstar** [comment]
Sorry for the long delay..

1. I do not have this issue, it's possibly another plugin interfering with the inventory. Try on a test server with no other plugins.

2. I have added a config option to toggle Seeker protection. See change a4a7450530812eb0f7673f8defc4075e65906007

3. Try with the latest ProtocolLib dev builds and latest LibsDisguises. I only run this on 1.8.3 now so I have no way to confirm how it works with older Spigot versions. Spigot 1649 is extremely old now (Sep 2014).
