### ISSUE TITLE
Hiders unable to strike Seeker and intermittently invisible.

### ISSUE THREAD

**Issue by elliswin** [addstar/BlockHunt#6]
Hello again!

I've been trying to get Blockhunt to work for us, and when I went over to the original authors page, saw you had been working on your own fork of this for your server, I asked which I should use as we have some issues and I've been advised to continue using your version of the plugin.

My problem is that Hiders are unable to strike the seekers, and hiders intermittently are invisible blocks, with just their drop shadow showing on the floor.

The versions we are using are:
Spigot MC: 1.8.3-R0.1 Snapshot
Blockhunt 0.2.1-b26 (from your download link)
ProtocolLib 3.6.3-snapshot-b114
LibsDisguises 8.3.2

I don't see any errors in the console when any of this happens, other than these issues everything else works fine.

Any advice on alternative versions etc. would be appreciated.

Ellis

**Comment by addstar** [comment]
I have added a config option to toggle Seeker protection. See change a4a7450530812eb0f7673f8defc4075e65906007

As for the block update issues, I recommend using a recent development build of ProtocolLib.
