### ISSUE TITLE
Hunters Can't Use Bow's To Damage Hiders And Hiders Can't Use Sword

### ISSUE THREAD

**Issue by JBuscus** [addstar/BlockHunt#9]
As in the title the Hunters Can't Harm Hiders With A Bow And Hiders Can't Use There Wooden Sword
Any Idea's?

Just so you know Hunters Can Still Use There Sword To Attack

Edit: Using Newest 1.8.7 build no errors in log

**Comment by addstar** [comment]
There are configuration settings (per arena) to change this behaviour.
Please see the comment of 1e38bd6b2970ab3354417cff2eff116509a4c709 for details.

**Comment by JBuscus** [comment]
Seekers still can't use bows to attack?

**Comment by JBuscus** [comment]
Here is my config 



Hunt:
  ==: BlockHuntArena
  maxPlayers: 42
  hidersWinCommands: []
  timeInLobbyUntilStart: 50
  minPlayers: 2
  timeUntilHidersSword: 30
  seekersCanHurtSeekers: false
  hidersCanHurtSeekers: true
  hidersCanHurtHiders: false
  seekersTakeFallDamage: false
  hidersTakeFallDamage: false
  spawnWarp:
    ==: BlockHuntLocation
    p: 1.5001619
    a: -269.51782
    w: minigames
    x: 381.05644772678784
    y: 27.0
    z: -252.43670297936322
  allowedCommands: []
  arenaName: Hunt
  amountSeekersOnStart: 1
  pos1:
    ==: BlockHuntLocation
    w: minigames
    x: 226.0
    y: 3.0
    z: -173.0
  pos2:
    ==: BlockHuntLocation
    w: minigames
    x: 386.0
    y: 33.0
    z: -333.0
  waitingTimeSeeker: 20
  seekersTokenWin: 10
  lobbyWarp:
    ==: BlockHuntLocation
    p: 1.2707114E-4
    a: -271.31653
    w: minigames
    x: 381.1567200745337
    y: 27.0
    z: -252.54866810282482
  seekersWinCommands: []
  killTokens: 8
  gameTime: 360
  disguiseBlocks:
  - ==: org.bukkit.inventory.ItemStack
    type: GLASS
  - ==: org.bukkit.inventory.ItemStack
    type: REDSTONE_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: PRISMARINE
    damage: 2
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: COBBLESTONE
  - ==: org.bukkit.inventory.ItemStack
    type: BEACON
  - ==: org.bukkit.inventory.ItemStack
    type: REDSTONE_LAMP_OFF
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
  - ==: org.bukkit.inventory.ItemStack
    type: WORKBENCH
  - ==: org.bukkit.inventory.ItemStack
    type: WOOD
  - ==: org.bukkit.inventory.ItemStack
    type: WOOL
    damage: 15
  - ==: org.bukkit.inventory.ItemStack
    type: LAPIS_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: COAL_ORE
  - ==: org.bukkit.inventory.ItemStack
    type: WOOL
    damage: 5
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_ORE
  - ==: org.bukkit.inventory.ItemStack
    type: GRASS
  - ==: org.bukkit.inventory.ItemStack
    type: HAY_BLOCK
  - ==: org.bukkit.inventory.ItemStack
    type: BOOKSHELF
  - ==: org.bukkit.inventory.ItemStack
    type: FURNACE
  - ==: org.bukkit.inventory.ItemStack
    type: TNT
  - ==: org.bukkit.inventory.ItemStack
    type: WOOL
  hidersWarp:
    ==: BlockHuntLocation
    p: 1.3499719
    a: 91.08957
    w: minigames
    x: 284.69648257712834
    y: 5.0
    z: -277.3816374195997
  blockAnnouncerTime: 45
  seekersWarp:
    ==: BlockHuntLocation
    p: 4.6500125
    a: 270.34467
    w: minigames
    x: 297.38212150845203
    y: 5.0
    z: -263.57686052585416
  hidersTokenWin: 50

**Comment by JBuscus** [comment]
Still cant attack seekers at all :/

**Comment by addstar** [comment]
Sorry but I'm confused by what you're actually wanting. You've said different things now. Can you explain exactly which situation you want and I can help you configure it.

**Comment by JBuscus** [comment]
Ok The hiders still can not use there sword to attack the Hunters at all with the config above, And the Hunters can Use There Sword to attack but the bow does no damage to the hiders. Is that better wording? sorry for confusing you.

**Comment by addstar** [comment]
With the {hidersCanHurtSeekers} option enabled, definitely hiders should be able to hurt seekers. Are you sure you're using the [latest development build](http://jenkins.addstar.com.au/job/BlockHunt) (29)? Also check you have no other plugins that might be blocking the attack. Are any players able to damage each other inside the arena (while not in a game)?

**Comment by JBuscus** [comment]
Yes players that are not OP can damage other people while not in the game and in the block hunt arenaarena and yes I am using the newest build and my other PVP type arena plugins work fine and do not conflict with this plugin

**Comment by JBuscus** [comment]
Do you want my LIBs Disguises config? I am using the newest version and Spigot 1.8.8 now

**Comment by JBuscus** [comment]
Also I have used this since 1.8.3 and it has worked the same the whole time which is good. The damage is the only issue my players complain about other than this your builds of this plugin are awesome thanks for keeping it alive ;D

**Comment by addstar** [comment]
You're welcome :grinning: 

And my apologies, it sounds like that could be a legitimate bug.. we don't allow hiders to hurt seekers on our server so it didn't get much testing. I'll look into it and get back to you.

**Comment by JBuscus** [comment]
Thank you so much! Awesome Dev :D

**Comment by addstar** [comment]
I think I found the issue.. it was a silly mistake :wink: 
Try out build 30, it should be better now.

**Comment by JBuscus** [comment]
OK awesome I shall try it out ASAP thanks addstar! :)
